spring:
  application:
    name: playmatch

  datasource:
    url: jdbc:postgresql://localhost:5434/playmatch
    username: postgres
    password: password
  # Added Redis Configuration Properties
  data:
    redis:
      host: localhost
      port: 6379
      password: "" # Leave empty or remove if no authentication is set on your local instance
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: TRACE

jwt:
  secret: YWJpbGl0eXNvbGlkbWVldHdoaWNoaHVtYW5zZW50ZnVsbHl3aG9wcg==
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
server:
  port: 8080