spring:
  application:
    name: playmatch

  datasource:
    url: jdbc:postgresql://localhost:5434/playmatch
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: TRACE

jwt:
  secret: YWJpbGl0eXNvbGlkbWVldHdoaWNoaHVtYW5zZW50ZnVsbHl3aG9wcg==
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
server:
  port: 8080