spring:
  application:
    name: playmatch

  datasource:
    url: jdbc:postgresql://localhost:5434/playmatch
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: TRACE

jwt:
  secret: YWJpbGl0eXNvbGlkbWVldHdoaWNoaHVtYW5zZW50ZnVsbHl3aG9wcg==
  expiration: 3600000
server:
  port: 8080